export default {
  menu: 'bars',
  isOpen: 'angle-down',
  isClosed: 'angle-right',
  loading: 'spinner fa-spin fa-5x',
  pending: 'spinner fa-spin',
  submit: 'check',
  error: 'exclamation',
  first: 'fast-backward',
  previous: 'step-backward',
  next: 'step-forward',
  last: 'fast-forward',
  close: 'times',
  filter: 'filter',
  group: 'th',
  exporter: 'file',
  check: 'check',
  sort: 'sort',
  sortAsc: 'sort-down',
  sortDesc: 'sort-up'
}
